### PR TITLE
Peter-added my name

### PR DESCRIPTION
**Pull request by WalkingHuman**
added my name

### CODE REVIEW

**Comment by RishonIlao** [comment]
trash

**Review by liapia99 — APPROVED** [review]
great

**Review by SeckMohameth — APPROVED** [review]
Fixed the code. Looks good to me

**Comment by liapia99** [comment]
great

**Review by RishonIlao — APPROVED** [review]
it's trash...but i wanna move on bruh

**Review by Dorian1218 — APPROVED** [review]
not gonna cap with you, this horrible. Do not implement this

**Review by RishonIlao — APPROVED** [review]
absolutely horrendous...approved

**Comment by SeckMohameth** [comment]
Not on my watch ❌.... I joke I joke. Welcome to the repo 🎉🏁

**Pull request merged**
